export enum IconEnum {
  THEME = 'icon_theme',
  BURGER = 'icon_burger',
  STAR = 'icon_star',
  STAR_SELECTED = 'icon_star_selected',
  MENU_HOME = 'icon_menu_home',
  MENU_ABOUT = 'icon_menu_about',
  MENU_PROFILE = 'icon_menu_profile',
  MENU_ARTICLE_FEED = 'icon_menu_feed',
  EYE = 'icon_eye',
  CALENDAR = 'icon_calendar',
  VIEW_TILE = 'icon_view_tile',
  VIEW_ROW = 'icon_view_row',
  NOTIFY = 'icon_notify',
}
