export { userReducer, userSlice, userAction } from './model/slice/userSlice'
export type { User } from './type/user.type'
export type { UserState } from './type/state.type'
// export { getUserAuthData } from './model/selector/getUserAuthData/getUserAuthData'
// export { getUserIsInited } from './model/selector/getUserIsInited/getUserIsInited'
export * from './model/selector'
