export { ProfileCardAsync as ProfileCard } from './ui/ProfileCard/ProfileCard.async'
export { ProfileState } from './type/state.type'
export { ProfileData } from './type/profile.data'
export { profileAction, profileReducer } from './model/slice/profileSlice'
export { fetchProfileData } from './model/service/fetchProfileData/fetchProfileData'
