export { ProfileCardAsync as ProfileCard } from './ui/ProfileCard/ProfileCard.async'
export type { ProfileState } from './type/state.type'
export type { ProfileData } from './type/profile.data'
export { profileAction, profileReducer } from './model/slice/profileSlice'
export { fetchProfileData } from './model/service/fetchProfileData/fetchProfileData'
export { updateProfileData } from './model/service/updateProfileData/updateProfileData'
export { selector } from './model/selector'
