name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn

      # - name: build production project
      #   run: yarn build:prod
      # - name: linting typescript
      #   run: yarn lint:code:check
      # - name: linting css
      #   run: yarn lint:style:check
      # - name: unit testing
      #   run: yarn test:unit
      #
      - name: build storybook
        run: yarn sb:build
      - name: screenshot testing
        run: yarn test:ui:ci

